spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
