spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:postgres://localhost/tacocloud
    username: tacocloud
    password: ${env.POSTGRES_PASSWORD}
  h2:
    console:
      enabled: false
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
logging:
  level:
    tacos: WARN
taco:
  order:
    page-size: 20
